# Data sources

We obtain three main datasets from NYC Open Data. Open Data is free public data published by New York City agencies and other partners, which collects all kinds of data in NYC.

In our project, we mainly consider about three types of datasets: COVID-19 datasets, which contain records of cases, deaths and vaccination populations; Crime datasets, which contain records of shooting, arrest and hate crime data in NYC; Air Quality dataset, which contains air quality data.

We will try to gain some insights from the above three different perspectives. We want to estimate the overall living condition across neighborhoods in New York City. After analyzing all these three perspectives, hopefully we may offer some advice on choosing the ideal neighborhood for people to live.

## COVID-19 Dataset

### Daily Counts of Cases, Hospitalizations, and Deaths.
Such dataset can be found on: https://data.cityofnewyork.us/Health/COVID-19-Daily-Counts-of-Cases-Hospitalizations-an/rc75-m7u3
https://github.com/nychealth/coronavirus-data

Key variables: `CASE_COUNT`, `HOSPITALIZED_COUNT`, and `DEATH_COUNT` among various demographics aspects across various boroughs.

### Vaccinated Population Data.
Such dataset can be found on: https://github.com/nychealth/covid-vaccine-data/tree/main/people#coverage-summary-allagescsv

Key variables: `RACE_ETHNICITY`, `AGE_GROUP`, `COUNT_PARTIALLY_CUMULATIVE`, `COUNT_FULLY_CUMULATIVE`, and `COUNT_1PLUS_CUMULATIVE` across `BOROUGH`.

## Crime Dataset

### Shooting Incident Data collected by NYPD.
Such dataset can be found on: https://data.cityofnewyork.us/Public-Safety/NYPD-Shooting-Incident-Data-Historic-/833y-fsy8
https://data.cityofnewyork.us/Public-Safety/NYPD-Shooting-Incident-Data-Year-To-Date-/5ucz-vwe8

Key variables: `PERP_AGE_GROUP`, `PERP_SEX`, `VIC_AGE_GROUP`, `VIC_SEX`, and `STATISTICAL_MURDER_FLAG` across `BORO` at `OCCUR_TIME`.

### Arrest Data collected by NYPD.
Such dataset can be found on: https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u
https://data.cityofnewyork.us/Public-Safety/NYPD-Arrest-Data-Year-to-Date-/uip8-fykc

Key variables: `LAW_CODE`, `AGE_GROUP`, `PERP_SEX`, and `PERP_RACE` across `ARREST_BORO` at `Record Create Date`.

### Hate Crimes Data collected by NYPD.
Such dataset can be found on: https://data.cityofnewyork.us/Public-Safety/NYPD-Hate-Crimes/bqiq-cu78

Key variables: `Law Code Category Description`, `Bias Motive Description`, and `Offense Description` across `County` at `ARREST_DATE`.

## Air Quality Dataset

### New York City Air Quality Surveillance Data:

This dataset contains information on New York City air quality surveillance data.

Air pollution is one of the most important environmental threats to urban populations and while all people are exposed, pollutant emissions, levels of exposure, and population vulnerability vary across neighborhoods. Exposures to common air pollutants have been linked to respiratory and cardiovascular diseases, cancers, and premature deaths. These indicators provide a perspective across time and NYC geographies to better characterize air quality and health in NYC.

Air quality is an important indicator of living wellness. Analyzing air quality data will help us to find a health place for people to live.

Air quality data contains these following key variables: 

```{r, echo  = FALSE}
Variable.name = c('Indicator ID', 'Measure', 'Geo Place Name', 'Time Period', 'Data Value')
Description = c('Identifier of the type of measured value', 'How the indicator is measured','Neighborhood name','Description of the time the data applies to', 'The actual data value for this indicator')
d = data.frame(Variable.name,Description)
knitr::kable(d, caption = "Key Variables in Air Quality Dataset",
             row.names = F,font_size = 10)
```
This dataset can be found on: https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r
