# Missing values

```{r, include=FALSE}
source("plot_missing.R")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Summary

NO missing values in air quality dataset and Covid-19 dataset. Some missing values in crimes dataset. See below...

## About Crimes Dataset

### Shooting

xxxx

```{r, echo = FALSE}
shooting_df <- read.csv("data/NYPD_Shooting_2020_2021.csv")
shooting_df[shooting_df == "" | shooting_df == "UNKNOWN"] <- NA
colSums(is.na(shooting_df)) %>% sort(decreasing = TRUE)
```

xxxx

```{r, results = 'hide', fig.height = 12, fig.width = 10}
plot_missing(shooting_df, percent = FALSE)
plot_missing(shooting_df, percent = TRUE)
```

### Arrest

xxxx

```{r, echo = FALSE}
arrest_df <- read.csv("data/NYPD_Arrest_2020_2021.csv")
arrest_df[arrest_df == "" | arrest_df == "UNKNOWN"] <- NA
colSums(is.na(arrest_df)) %>% sort(decreasing = TRUE)
```

xxxx

```{r, results = 'hide', fig.height = 8, fig.width = 10}
plot_missing(arrest_df, percent = FALSE)
plot_missing(arrest_df, percent = TRUE)
```


### Hate Crime

xxxx

```{r, echo = FALSE}
hate_df <- read.csv("data/NYPD_Hate_Crimes_2020_2021.csv")
colSums(is.na(hate_df)) %>% sort(decreasing = TRUE)
```

xxxx

```{r, results = 'hide', fig.height = 10, fig.width = 12}
plot_missing(hate_df, percent = FALSE)
plot_missing(hate_df, percent = TRUE)
```
